# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://hyosunghan.github.io/blog
date_format: "ordinal"
title: 个人博客
subtitle: "HelloWorld"
description: "test"
keywords: 博客, hyosunghan, 程序员
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: hyosunghan/blog
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-08-01
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: HyosungHan
organization: 
organization_url: 
github_username: hyosunghan
location: Xi'an, China
email: ihyosunghan@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: hyosunghan
    repo: blogtalk
    oauth:
        client_id: 72ed8a6cacddf348975d
        client_secret: cd2484a96385b78da573517cf06202efb80c0728
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: hyosunghan
    repo: blogtalk
    clientID: 72ed8a6cacddf348975d
    clientSecret: cd2484a96385b78da573517cf06202efb80c0728
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
